fixed: some users (specifically on mac) can not open vs-code with the code command

diff --git a/manage/himolde b/manage/himolde
--- a/manage/himolde
+++ b/manage/himolde
@@ -47,10 +47,10 @@ _mainloop () {
     "7. Install Open edX" \
     "8. Create admin user for Open edX" \
     '9. Install Nitro' \
-    '10. initialization of Nitro' \
-    "11. Add page $WEB_PORTAL_ROOT to nitro" \
-    "12. Run composer for $WEB_PORTAL_ROOT" \
-    "13. Fix write permission for PHP in $WEB_PORTAL_ROOT/" \
+    '10. Run Nitro init' \
+    "11. Add project in $WEB_PORTAL_ROOT to nitro" \
+    "12. Run composer inside $WEB_PORTAL_ROOT" \
+    "13. Fix write permission for PHP inside $WEB_PORTAL_ROOT/" \
     "14. Bind-mount $EDX_PLATFORM_ROOT into the Open edX lms and cms containers" \
     "15. Add $_HOST_DEV_WEB_PORTAL to docker network: tutor_dev_default" \
     "16. Remove $_HOST_DEV_WEB_PORTAL from docker network: tutor_dev_default" \
@@ -164,9 +164,17 @@ _mainloop () {
     exit
 
   elif [[ $_choice == '19' ]]; then
-    cd $WEB_PORTAL_ROOT
-    code .
-    cd $HOME
+    if ! _is_command code; then
+      echo 'Can`t open VS-Code'
+      echo 'Fix this by opening VS-Code'
+      echo 'Then open the Command Palette (View -> Command Palette)'
+      echo 'Type shell command to find Shell Command: Install 'code' command in PATH command'
+      echo 'Then re-try this option'
+    else
+      cd $WEB_PORTAL_ROOT
+      code .
+      cd $HOME
+    fi
 
   fi
 }
